api:
  container_name: camembert_api
  build: .
  ports:
    - 80:80
  links:
    - mongo

mongo:
  container_name: camembert_mongo
  build: docker/mongo/.
  command: mongod --smallfiles --quiet --logpath=/dev/null --dbpath=/data/db

mongo-seed:
  container_name: camembert_mongo_seed
  build: docker/mongo-seed/.
  links:
    - mongo